version: '3.9'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: congestion
      MONGO_INITDB_ROOT_PASSWORD: congestion
      MONGO_INITDB_DATABASE: volvo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
